### ISSUE TITLE
Missing bits header under WSL

### ISSUE THREAD

**Issue by gtoal** [siliconsam/imp2022#3]
In file included from pass3coff.c:10:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

- this may just be a documentation issue, but when compiling under WSL2 this header was not present.  I think this was because my WSL2 implementation is 64-bits only and does not have the headers for the -m32 option even though the -m32 option is present in the compiler.  It is fixed by sudo apt-get install gcc-multilib (which *is* mentioned in the readme, it's just not obvious by the time the error happens that that was the cause of it).  I guess I can add a better test for multilib being absent in the install script we're working on.

**Comment by siliconsam** [comment]
The documentation describing the pre-requisites for the compiler environment indicates that the gcc-multilib is required for building 32-bit code in a 64-bit version of Linux.
A quick Google search for the error generated, provides suggestions that the gcc-multilib package is missing when attempting to compile 32-bit code.
